import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../config/app_constants.dart';

const _termsContent = r"""
# Terms of Service

**RiseUp — AI Wealth Mentor**
**ChAs Tech Group**
**Last updated: January 2025**

---

## 1. Acceptance of Terms

By creating a RiseUp account or using the app, you agree to these Terms of Service. If you do not agree, do not use RiseUp.

---

## 2. About RiseUp

RiseUp is an AI-powered financial education and mentoring platform. We provide:
- Personalised income task suggestions
- Skill-building courses
- AI-generated wealth roadmaps
- Community features

**Important**: RiseUp is an educational tool, **not a licensed financial advisor**. The AI recommendations are for informational purposes only and should not be treated as professional financial advice.

---

## 3. Eligibility

You must be at least **13 years old** to use RiseUp. By using the app, you confirm you meet this requirement.

---

## 4. Your Account

- You are responsible for keeping your login credentials secure
- You must provide accurate information when registering
- One account per person — creating multiple accounts is prohibited
- You may not share your account with others

---

## 5. Acceptable Use

You agree **not** to:
- Use RiseUp for any illegal purpose
- Attempt to hack, reverse-engineer, or damage our systems
- Spam, harass, or abuse other community members
- Post false, misleading, or harmful content
- Use automated bots to access the service
- Circumvent rate limits or security measures

Violations may result in immediate account suspension.

---

## 6. AI Disclaimer

The RiseUp AI mentor:
- Provides educational information and general guidance only
- Is **not** a licensed financial advisor, investment advisor, or wealth manager
- May make mistakes — always verify important financial decisions independently
- Responses are generated by third-party AI models (Groq, Google, OpenAI, Anthropic)

**ChAs Tech Group accepts no liability for financial decisions made based on AI suggestions.**

---

## 7. Payments & Subscriptions

- Premium subscriptions are processed by **Flutterwave**
- Subscription fees are charged in your chosen currency
- **No refunds** on subscription fees once a billing period has started, except where required by law
- You may cancel your subscription at any time — access continues until the end of the billing period
- Prices may change with 30 days' notice

---

## 8. Advertisements

- Free users see advertisements powered by Google AdMob (mobile) and Google AdSense (web)
- Premium subscribers see fewer or no ads
- We do not control the content of third-party advertisements

---

## 9. Intellectual Property

- All RiseUp content, branding, and code is owned by **ChAs Tech Group**
- You may not copy, reproduce, or distribute RiseUp content without written permission
- You retain ownership of content you create (posts, task completions, etc.)
- By posting in the community, you grant us a licence to display that content

---

## 10. Termination

We may suspend or terminate your account if you violate these terms. You may delete your account at any time via Settings → Delete Account.

---

## 11. Limitation of Liability

To the maximum extent permitted by law, ChAs Tech Group is not liable for:
- Any financial losses resulting from following AI advice
- Service interruptions or data loss
- Third-party content or services

Our total liability to you shall not exceed the amount you paid us in the 12 months before the claim.

---

## 12. Governing Law

These terms are governed by the laws of the **Federal Republic of Nigeria**. Disputes shall be resolved in Lagos State courts.

---

## 13. Changes to Terms

We will notify you of material changes via email and in-app notice. Continued use after the effective date means you accept the changes.

---

## 14. Contact

**ChAs Tech Group**
Lagos, Nigeria
📧 legal@chastech.ng
""";

class TermsScreen extends StatelessWidget {
  const TermsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.bgDark,
      appBar: AppBar(
        title: Text('Terms of Service', style: AppTextStyles.h3),
        backgroundColor: AppColors.bgDark,
      ),
      body: Markdown(
        data: _termsContent,
        styleSheet: MarkdownStyleSheet(
          h1: AppTextStyles.h2.copyWith(color: AppColors.primary),
          h2: AppTextStyles.h3,
          h3: AppTextStyles.h4,
          p: AppTextStyles.body,
          tableBody: AppTextStyles.bodySmall,
          tableBorder: TableBorder.all(color: AppColors.bgSurface),
          tableColumnWidth: const FlexColumnWidth(),
          blockquoteDecoration: BoxDecoration(
            color: AppColors.bgCard,
            border: Border(left: BorderSide(color: AppColors.warning, width: 3)),
          ),
          horizontalRuleDecoration: BoxDecoration(
            border: Border(bottom: BorderSide(color: AppColors.bgSurface)),
          ),
        ),
        onTapLink: (text, href, title) async {
          if (href != null) {
            final uri = Uri.parse(href);
            if (await canLaunchUrl(uri)) launchUrl(uri);
          }
        },
      ),
    );
  }
}
